export const SocketEvents = {
  // Client -> Server
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  SUBMIT_BOARD: 'SUBMIT_BOARD',
  SELECT_NUMBER: 'SELECT_NUMBER',
  SEND_CHAT: 'SEND_CHAT',
  REQUEST_PLAY_AGAIN: 'REQUEST_PLAY_AGAIN',
  LEAVE_ROOM: 'LEAVE_ROOM',

  // Server -> Client
  ROOM_CREATED: 'ROOM_CREATED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  GAME_STARTED: 'GAME_STARTED',
  TURN_CHANGED: 'TURN_CHANGED',
  NUMBER_SELECTED: 'NUMBER_SELECTED',
  GAME_UPDATED: 'GAME_UPDATED',
  GAME_OVER: 'GAME_OVER',
  CHAT_RECEIVED: 'CHAT_RECEIVED',
  ERROR: 'ERROR',
} as const;
